# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export USER=brenden

# Path to your oh-my-zsh installation.
export ZSH="/root/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="fino-time"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# PATH
# node.js in path
export PATH=$PATH:/home/brenden/Software/node-v14.18.1-linux-x64/bin
# pyenv in path
export PATH=/home/brenden/.pyenv/bin:$PATH
export PATH=/home/brenden/.pyenv/shims:$PATH

# zsh
alias zrc="vim ~/.zshrc"
alias szrc="source ~/.zshrc"

# shell shorthand
alias cl="clear"
alias grni="grep -rni"
alias ap="ansible-playbook"
alias tf="terraform"

# edit dotfiles
alias vrc="vim ~/.vimrc"
alias sshc="vim ~/.ssh/config"

# git
alias gdom="git diff origin/master"
alias gdm="git diff master"

# apt
alias aud="sudo apt update"
alias aug="sudo apt upgrade"
alias augy="sudo apt upgrade -y"
alias ai="sudo apt install"
alias aiy="sudo apt install -y"
alias aps="sudo apt search"
alias aall="aud && augy"

# python
alias py="python"
alias py3="python3"
alias ipy="ipython"
alias calc="ipy -c"
alias flr="flask run"

# filesystem navigation
alias cdg="cd ~/git"
alias cdl="cd ~/git/LS"
alias dwn="cd ~/Downloads"
alias doc="cd ~/Documents"
alias cds="cd ~/Software"

# network troubleshooting
alias pg="ping 8.8.8.8"
alias trg="traceroute 8.8.8.8"
alias nsl="nslookup"
alias chkip="dig +short myip.opendns.com @resolver1.opendns.com"

# Docker
alias dps="docker container ls"
alias ds="docker stop"
alias dp="docker container prune -f"
alias dip="docker image prune -f"
alias dlf="docker logs --follow"
alias dims="docker image ls"
alias dimr="docker image rm"
alias dc="docker-compose"
alias dcu="docker-compose up"
alias dcd="docker-compose up -d"
alias dcua="docker-compose up --abort-on-container-exit"
alias docksock="sudo chmod a+w /var/run/docker.sock"

# math
function math {
  echo "scale=2;$1" | bc -l
}

alias mkpass="pwgen -cynsB"
